version: '3.7'
#
services:
  iris:
    build:
      context: ./build
    image: dpmeister/irisdemo:simple
    hostname: iris
    command: --ISCAgent false --monitorCPF false --key /ISC/iris.key
    ports:
    - "52773:52773"

    volumes:
    - ./cpf:/home/irisowner/cpf
    - ./:/ISC

    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/common.cpf

  webgateway:
    image: containers.intersystems.com/intersystems/webgateway:2023.2.0.227.0
    init: true
    container_name: webgateway
    hostname: webgateway
    ports:
    - "8080:80"
    environment:
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - ./webgateway:/webgateway-shared
