apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: c2
  region: ap-northeast-1
availabilityZones: ["ap-northeast-1a", "ap-northeast-1c", "ap-northeast-1d"]
nodeGroups:
  - name: arbiter
    labels: { speedtest/node-type: iris-arbiter }
    instanceType: r5.large
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
  - name: iris-nodes
    labels: { speedtest/node-type: iris }
    instanceType: r5.xlarge
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
