apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: speedtest-cluster
  region: ap-northeast-1
  version: "1.27"
# see https://eksctl.io/usage/addons/
iam:
  withOIDC: true
addons:
- name: aws-ebs-csi-driver
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
# if you need efs 
- name: aws-efs-csi-driver
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy
availabilityZones: ["ap-northeast-1a", "ap-northeast-1c", "ap-northeast-1d"]
nodeGroups:
  - name: arbiter-node
    labels: { speedtest/node-type: iris-arbiter }
    instanceType: r5.large
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    availabilityZones: ["ap-northeast-1d"]
  - name: iris-nodes
    labels: { speedtest/node-type: iris }
    instanceType: r5.xlarge
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    availabilityZones: ["ap-northeast-1a", "ap-northeast-1c"]
  - name: ui
    labels: { speedtest/node-type: master-ui }
    instanceType: r5.large
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    availabilityZones: ["ap-northeast-1d"]
  - name: ingest
    labels: { speedtest/node-type: ingest }
    instanceType: r5.large
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    availabilityZones: ["ap-northeast-1d"]
  - name: query
    labels: { speedtest/node-type: query  }
    instanceType: r5.large
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    availabilityZones: ["ap-northeast-1d"]
