apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: c2
  region: ap-northeast-1
availabilityZones: ["ap-northeast-1a", "ap-northeast-1c", "ap-northeast-1d"]
nodeGroups:
- name: iris-nodes
  labels: { speedtest/node-type: iris }
  instanceType: r5.2xlarge
  minSize: 2
  maxSize: 2
  desiredCapacity: 2
- name: masterui-group
  labels: { speedtest/node-type: master-ui }
  instanceType: c5.xlarge
  minSize: 1
  maxSize: 1
  desiredCapacity: 1
- name: ingest-group
  labels: { speedtest/node-type: ingest }
  instanceType: c5.xlarge
  minSize: 2
  maxSize: 2
  desiredCapacity: 2
- name: query-group
  labels: { speedtest/node-type: query }
  instanceType: c5.xlarge
  minSize: 2
  maxSize: 2
  desiredCapacity: 2
