apiVersion: v1
kind: Service
metadata:
  name: my-iris
  labels:
    app: my-iris
spec:
  type: LoadBalancer
  ports:
  - port: 52773
    targetPort: 52773
    protocol: TCP
    name: http
  selector:
    app: my-iris
