apiVersion: v1
kind: Service
metadata:
  name: iris-compute
spec:
  selector:
    intersystems.com/component: compute
    intersystems.com/kind: IrisCluster
    intersystems.com/name: iris-vs2021
    intersystems.com/role: iris
  ports:
  - name: superserver
    port: 1972
    protocol: TCP
    targetPort: superserver
  - name: webserver
    port: 80
    protocol: TCP
    targetPort: webserver
  type: LoadBalancer
