apiVersion: v1
kind: Service
metadata:
  name: simple-server
  labels:
    app: simple-server
spec:
  selector:
    app: simple-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  #type: ClusterIP
  #type: NodePort
  type: LoadBalancer
