apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: iris-ssd-storageclass
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
volumeBindingMode: WaitForFirstConsumer
