apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: iris-vs2021
spec:
  licenseKeySecret:
    name: iris-key-secret
  configSource:
    name: iris-cpf
  imagePullSecrets:
    - name: dockerhub-secret
  storageClassName: iris-ssd-storageclass
  volumeClaimTemplates:
    - metadata:
        name: extra-disk
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi

  topology:
    arbiter:
      image: containers.intersystems.com/intersystems/arbiter:2022.1.0.209.0
      podTemplate:
        spec:
          imagePullSecrets:
            - name: dockerhub-secret
      preferredZones:
        - japaneast-1
    data:
      shards: 1
      mirrored: true
      image: containers.intersystems.com/intersystems/iris:2022.1.0.209.0
      podTemplate:
        spec:
          args: 
            - --check-caps false
      preferredZones:
        - japaneast-2
        - japaneast-3
      updateStrategy:
        type: RollingUpdate
    compute:
      image: containers.intersystems.com/intersystems/iris:2022.1.0.209.0
      podTemplate:
        spec:
          args: 
            - --check-caps false
      replicas: 2
      preferredZones:
        - japaneast-2
        - japaneast-3
    sam:
      image: containers.intersystems.com/intersystems/sam:1.1.0.107

  serviceTemplate:
    spec:
      type: LoadBalancer
