apiVersion: v1
kind: Service
metadata:
  name: my-iris
  labels:
    app: my-iris
spec:
  type: LoadBalancer
  ports:
  - port: 52773
    targetPort: 52773
    protocol: TCP
    name: http
  selector:
    app: my-iris
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iris
spec:
  selector:
    matchLabels:
      app: my-iris # .spec.template.metadata.labelsの値と一致する必要があります
  serviceName: "my-iris"
  replicas: 2
  template:
    metadata:
      labels:
        app: my-iris # .spec.selector.matchLabelsの値と一致する必要があります
    spec:
      securityContext: 
        fsGroup: 51773
      terminationGracePeriodSeconds: 10
      containers:
      - name: my-iris
        image: containers.intersystems.com/intersystems/iris-community:2022.1.0.209.0
        args: 
        - --check-caps false # 2022.2 and later won't need this
        ports:
        - containerPort: 1972
        - containerPort: 52773
        env:
        - name: ISC_CPF_MERGE_FILE
          value: /irissys/cpf/merge.cpf
        - name: ISC_DATA_DIRECTORY
          value: /DATA/IRIS
        volumeMounts:
        - mountPath: /irissys/cpf/
          name: iris-cpf
        - mountPath: /DATA
          name: dbv
      volumes:
      - configMap:
          defaultMode: 420
          name: iris-merge-cpf
        name: iris-cpf
  volumeClaimTemplates:
  - metadata:
      name: dbv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: iris-ssd-storageclass
      resources:
        requests:
          storage: 10Gi