apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: iris-vs2021
spec:
  licenseKeySecret:
    name: iris-key-secret
  configSource:
    name: iris-cpf-userimage
  imagePullSecrets:
    - name: dockerhub-secret-userimage
  storageClassName: iris-ssd-storageclass
  volumeClaimTemplates:
    - metadata:
        name: extra-disk
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  updateStrategy:
    type: RollingUpdate
  serviceTemplate:
    spec:
      type: LoadBalancer

  topology:
    arbiter:
      image: dpmeister/irisdemo:arbiter-2022.1.0.209.0
      preferredZones:
        - japaneast-1
    data:
      #shards: 1
      mirrored: true
      image: dpmeister/irisdemo:simple
      podTemplate:
        spec:
          args: 
            - --check-caps false
      preferredZones:
        - japaneast-2
        - japaneast-3
    compute:
      image: dpmeister/irisdemo:iris-2022.1.0.209.0
      podTemplate:
        spec:
          args: 
            - --check-caps false
      replicas: 2
