apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: iris-vs2021
spec:
  passwordHash: 'd8191b3c433ed48c7cd60cb7a4b1bfd3068b38db,t6jhs1sc'
  licenseKeySecret:
    name: iris-key-secret
  configSource:
    name: iris-cpf
  topology:
    arbiter:
      image: containers.intersystems.com/intersystems/arbiter:2020.3.0.221.0
      preferredZones:
        - japaneast-1
      podTemplate:
        spec:
          imagePullSecrets:
            - name: dockerhub-secret
    data:
      shards: 1
      mirrored: true
      image: containers.intersystems.com/intersystems/iris:2020.3.0.221.0
      preferredZones:
        - japaneast-2
        - japaneast-3
      podTemplate:
        spec:
          imagePullSecrets:
            - name: dockerhub-secret
      updateStrategy:
        type: RollingUpdate
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: iris-ssd-storageclass
    compute:
      image: containers.intersystems.com/intersystems/iris:2020.3.0.221.0
      replicas: 2
      preferredZones:
        - japaneast-2
        - japaneast-3
      podTemplate:
        spec:
          imagePullSecrets:
            - name: dockerhub-secret
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: iris-ssd-storageclass
  serviceTemplate:
    spec:
      type: LoadBalancer
