apiVersion: v1
kind: Service
metadata:
  name: simple-server
  labels:
    app: simple-server
spec:
  selector:
    app: simple-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
spec:
  selector:
    matchLabels:
      app: simple-server
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-server
    spec:
      containers:
      - name: simple-server
        image: dpmeister/irisdemo:simple-server
        imagePullPolicy: "Always"
        env:
        # BASEURL_GETはECP Clientを束ねたbalancerに向けたいが、現状はそうなっていない
        - name: BASEURL_GET
          value: http://iris-vs2021-compute-0.iris-svc.default.svc.cluster.local
        - name: BASEURL_POST
          value: http://iris-vs2021-data-0-0.iris-svc.default.svc.cluster.local
        - name: TZ
          value: JST-9
      imagePullSecrets:
        - name: dockerhub-secret

