name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: dpmeister/irisdemo

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into docker registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Log into isc registry
        run: echo "${{ secrets.ISCREPO_TOKEN }}" | docker login -u ${{ secrets.ISCREPO_USERNAME }} containers.intersystems.com --password-stdin

      - name: Build image
        run: docker build ./build --file build/Dockerfile --tag image

      - name: Push image
        run: |
          IMAGE_ID=$IMAGE_NAME

          docker tag image $IMAGE_ID:simple
          docker push $IMAGE_ID:simple
